
--PROJETAR TODO USUARIOS QUE NAO TEM PADRINHO
SELECT * FROM USUARIO WHERE NUMERO_TELEFONE_PADRINHO IS NULL;

--PROJETAR TODOS USUARIOS VIP 
SELECT * FROM USUARIO WHERE EH_VIP = 1;

--PROJETAR TODOS USUARIOS NAO VIP 
SELECT * FROM USUARIO WHERE EH_VIP = 0;

--EMAIL DE TODOS USUARIOS
SELECT EMAIL FROM USUARIO;

--TODOS CUPONS JA RECEBIDOS PELOS USUARIOS
SELECT DISTINCT NOME_CODIGO FROM GANHA;

--O NOME E CNPJ DE TODOS RESTAURANTES
SELECT E.NOME, E.CNPJ FROM RESTAURANTE E;

--ENTREGADOR DO APP QUE TEM NOTA MAIOR QUE 4
SELECT * FROM ENTREGADOR WHERE NOTA > 4;

--TODOS PRATOS QUE TEM PRECO ENTRE 10 E 30
SELECT * FROM PRATO WHERE PRECO BETWEEN 10 AND 30;

--TODOS USUARIOS QUE TEM DDD 81
SELECT * FROM USUARIO WHERE NUMERO_TELEFONE LIKE '81%';

--TODOS USUARIOS QUE NAO TEM PADRINHOS
SELECT * FROM USUARIO WHERE NUMERO_TELEFONE_PADRINHO IS NULL;

--TODOS PEDIDOS QUE FORAM PEDIDOS COM CUPOM
SELECT * FROM PEDIDO WHERE NOME_CODIGO_CUPOM IS NOT NULL

-- PEDIDOS COM O PREÇO MAIOR QUE 90
SELECT * FROM PEDIDO WHERE PRECO > 90.0

--TODOS CEP DOS USUARIOS
SELECT A.CEP ,E.NUMERO_TELEFONE FROM ENDERECO A INNER JOIN USUARIO E ON A.NUMERO_TELEFONE = E.NUMERO_TELEFONE
